server:
  port: 9002

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: message-service

spring:
  application:
    name: message-service
  profiles:
    active: message,pg
